# General
title: John Spantouris - Portfolio
description: Personal portfolio
og_description: Portfolio page of John Spantouris

# Hero Title
username: John Spantouris
typing_text: Lead Software Engineer - Game Developer

# Social
email: john.spantouris@gmail.com
github_username: spantouris
linkedin_username: spantouris
itchio_username: spantouris
discord_server_url: https://discord.gg/k7EJSAkWDG

# About me
show_aboutme_card: true
about_me_title: About Me
about_me_description: My name is <b>John Spantouris</b>, I was born and currently live in Athens, Greece. Currently working as a Lead Software Engineer for <a href="https://www.pobuca.com" class="highlight-link" target="_blank" rel="noreferrer">Pobuca</a> building Web Applications with .NET on Microsoft Azure. Hobbyist game developer since 2013.

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: false
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: https://example.com/

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: false
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projects
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: false
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# Contact
show_contact_card: true
contact_title: Contact
contact_description: Feel free to contact me for any exciting project you may have <a class="highlight-link" href="mailto:john.spantouris@gmail.com" target="_blank" rel="noreferrer">here</a> or for any job opportunity you think I am a fit for. Don't forget to join our Greek Artist Discord Community.

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
