# General
title: John Spantouris - Portfolio
description: Personal portfolio
og_description: Portfolio page of John Spantouris

# Hero Title
username: John Spantouris
typing_text: Software Engineer - Game Developer

# Social
email: john.spantouris@gmail.com
github_username: spantouris
linkedin_username: spantouris
itchio_username: spantouris
discord_server_url: https://discord.gg/dxewRGj7hb

# About me
show_aboutme_card: true
about_me_title: About Me
about_me_description: My name is <b>John Spantouris</b>, born and living in Athens, Greece. Software Engineer for <a href="https://microsoft.com" class="highlight-link" target="_blank" rel="noreferrer">Microsoft</a>, building desktop Applications with .NET. Hobbyist game developer since 2013.

# Timeline
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Life Events

# PROJECTS SECTION
show_projects_card: true
projects_title: Projects

# Contact
show_contact_card: true
contact_title: Contact
contact_description: Do you have any exciting project or a job opportunity that you think I may be a good fit for? Feel free to contact me <a class="highlight-link" href="mailto:john.spantouris@gmail.com" target="_blank" rel="noreferrer">here</a>. Don't forget to join our <i>Greek Artist Discord Community</i> as well if you'd like clicking the discord link below 😁

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
